import type { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema11714900000000 implements MigrationInterface {
  name = "InitialSchema11714900000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "specialties" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" character varying NOT NULL,
        "icon" character varying NOT NULL DEFAULT '',
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_specialties_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_specialties_name" UNIQUE ("name")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "doctors" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" character varying NOT NULL,
        "specialtyId" integer NOT NULL,
        "hospital" character varying NOT NULL,
        "city" character varying NOT NULL,
        "exp" integer NOT NULL DEFAULT 0,
        "fee" integer NOT NULL DEFAULT 0,
        "advanceFee" integer NOT NULL DEFAULT 0,
        "totalSeats" integer NOT NULL DEFAULT 0,
        "usedSeats" integer NOT NULL DEFAULT 0,
        "rating" numeric(2,1) NOT NULL DEFAULT 4.5,
        "degrees" character varying NOT NULL DEFAULT '',
        "chamberAddress" character varying,
        "rrule" character varying,
        "nextAppointment" TIMESTAMPTZ,
        "chamberOpenTime" character varying,
        "chamberCloseTime" character varying,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_doctors_id" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_doctors_advanceFee_nonnegative" CHECK ("advanceFee" >= 0),
        CONSTRAINT "FK_doctors_specialty" FOREIGN KEY ("specialtyId") REFERENCES "specialties"("id") ON DELETE RESTRICT
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "users" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "email" character varying NOT NULL,
        "password" character varying NOT NULL,
        "role" character varying NOT NULL DEFAULT 'doctor',
        "doctorId" integer,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_users_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_users_email" UNIQUE ("email"),
        CONSTRAINT "UQ_users_doctorId" UNIQUE ("doctorId"),
        CONSTRAINT "FK_users_doctor" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE SET NULL
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "appointments" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "userId" integer,
        "doctorId" integer NOT NULL,
        "patientName" character varying NOT NULL,
        "patientPhone" character varying NOT NULL,
        "appointmentDate" date NOT NULL,
        "slot" character varying NOT NULL,
        "fee" integer NOT NULL,
        "status" character varying NOT NULL DEFAULT 'confirmed',
        "paymentMethod" character varying NOT NULL DEFAULT 'online',
        "paymentChoice" character varying NOT NULL DEFAULT 'full',
        "paymentStatus" character varying NOT NULL DEFAULT 'paid',
        "paidAmount" integer,
        "amountDue" integer NOT NULL DEFAULT 0,
        "paidByUserId" integer,
        "paidAt" TIMESTAMPTZ,
        "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_appointments_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_appointments_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL,
        CONSTRAINT "FK_appointments_doctor" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_appointments_paid_by_user" FOREIGN KEY ("paidByUserId") REFERENCES "users"("id") ON DELETE SET NULL
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS "appointments"');
    await queryRunner.query('DROP TABLE IF EXISTS "users"');
    await queryRunner.query('DROP TABLE IF EXISTS "doctors"');
    await queryRunner.query('DROP TABLE IF EXISTS "specialties"');
  }
}
